### ISSUE TITLE
httpie only?

### ISSUE THREAD

**Issue by robbihun** [dogeared/OZorkAuth#2]
Is this designed to only work in httpie? I tried using Postman to do the password flow and even cURL and neither worked for me to request an access and refresh token - i receive "invalid_client"

![image](https://cloud.githubusercontent.com/assets/138997/15196662/0ef0625c-1793-11e6-8a3b-1ffeff59cb0b.png)

**Comment by dogeared** [comment]
Hi @robbihun - It's definitely not HTTPie only. This curl command works for me:

```
curl -X POST \
  -H "Origin:https://ozorkauth.herokuapp.com"  \
  https://ozorkauth.herokuapp.com/v1/a \
  -d grant_type=password -d username=<email> -d password=<password>
```

I'm having the same problem with Postman that you are. I noticed on inspection, that Postman sets the `Origin` header regardless of what you set it to be:

![image](https://cloud.githubusercontent.com/assets/364562/15199324/44302688-17ab-11e6-91e8-b60e29c5b1f6.png)

I guess that makes sense, since Postman is a browser extension, but it is annoying.

I've heard good things about [Fiddler](http://www.telerik.com/fiddler), but I have not used it myself.

Let me know if you can at least get curl working!

**Comment by dogeared** [comment]
Quick follow up:

The Postman docs explain why you can't override the `Origin` header: https://www.getpostman.com/docs/requests

They do have a native mac app that will work.

**Comment by robbihun** [comment]
Makes sense, thanks!
